name: jejom-llama-debbie
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - python=3.12.5
  - pip:
      - flask==3.0.3
      - flask-cors==4.0.1
      - geopy==2.4.1
      - gitpython==3.1.43
      - json_repair==0.28.0
      - llama-index==0.10.65
      - llama-index-agent-openai==0.2.9
      - llama-index-cli==0.1.13
      - llama-index-core==0.10.65
      - llama-index-embeddings-huggingface==0.2.3
      - llama-index-embeddings-nvidia==0.1.5
      - llama-index-embeddings-openai==0.1.11
      - llama-index-embeddings-upstage==0.1.3
      - llama-index-llms-openai==0.1.29
      - llama-index-llms-openai-like==0.1.3
      - llama-index-llms-groq==0.1.4
      - llama-index-llms-nvidia==0.1.4
      - llama-index-llms-upstage==0.1.4
      - llama-index-llms-vllm==0.1.9
      - llama-index-multi-modal-llms-openai==0.1.9
      - llama-index-postprocessor-nvidia-rerank==0.1.5
      - llama-index-readers-file==0.1.33
      - llama-index-readers-llama-parse==0.1.6
      - llama-index-vector-stores-milvus==0.1.23
      - llama-parse==0.4.9
      - llamaindex-py-client==0.1.19
      - openai==1.40.6
      - pydantic==2.8.2
      - pymilvus==2.4.5
      - pypdf==4.3.1
      - python-dotenv==1.0.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - scikit-learn==1.5.1
      - torch==2.4.0
      - tavily-python==0.5.0
      - google-search-results==2.4.2
      - serpapi==0.1.5
      # - googlemaps
      # - googlemaps==4.10.0